hospitalName: ''
doctorName: ''
fileName: ''
shiftBeginning:
    dayOffset: 0
    time: '00:00'
shiftEnding:
    dayOffset: 0
    time: '00:00'
patients:
    - name: ''
      birthdate: ''
      complaint: ''
      metrics: ''
      notes: ''
      appliedHelp: ''
